### ISSUE TITLE
Licensing of this work

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#1]
I'd like to add an open-source license to our project, what do you guys think ? 

Here are my suggestions : 

MIT - Is a really simple, easy to understand open-source license. It mainly says, "do whatever you want this this code, just don't sue me"

Apache License 2.0 - Pretty similar to MIT, but has some additional terms to prevent patent trolling. 

GPL v2.0 - This is a strong copy-left license by fsf. It's main concern is code-sharing and free-software. Anyone who uses this software must also use this license to license their work, i.e. they must share their improvements and they must make it open-source.

GPL v3.0 - This is a strong copy-left license by fsf.com. It's mainly an addition over gpl v2.0 and has some terms to prevent tivoisation. Apart from sharing the contributions, users must also provide clear intructions to get the software working in their own environment. 

More information on licenses here: 

https://choosealicense.com/

Thanks!

**Comment by umurtrky** [comment]
I guesss MIT is the best and the simplest choice for our project. As I know most of the open source university projects like ours use this one. (Correct me if I am wrong.)

The article below gives information on licensing a repository. It mentions the link Onat provided also.

[Licensing a repository](https://help.github.com/articles/licensing-a-repository/)

Have a nice day!

**Comment by muharremunver** [comment]
I would prefer to use the simplest and most popular one so I am OK with MIT.

**Comment by onatbas** [comment]
If there's no objection to this, I'm marking this as complete.
