### ISSUE TITLE
Homework 2: Requirements Elicitation

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#11]
1. [x] Identify the requirements and document them. They must be written as formal requirements that include the overall description and specific requirements of your project.

2. [x] Document the requirements on your project repository.

3. [x] Be prepared to present the requirements and ask any questions you have identified during the elicitation phase. Also, be prepared to document the feedback you get from your customer.

**Comment by onatbas** [comment]
I think we have enough data to consider this done, am i right?

**Comment by umurtrky** [comment]
I added some definitions to the definitions part. You may edit it if you think there is anything wrong.

**Comment by muharremunver** [comment]
I added two different requirements too. We can accept them if all group confirm.

**Comment by ecada** [comment]
I added 8 additional questions 5 days ago thus I think we can close this issue.
