### ISSUE TITLE
Mockups Page Candidate

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#12]
Hello, everyone. 

I've created some mockups this week to give us a starting point in the design, hopefully, that's alright. I've created a wiki page (didn't add it to sidebar yet!) and created a scenario in which two people are creating annotations and history items etc. 

https://github.com/SWE574-Nerds/friendly-eureka/wiki/Mockups-%26-Designs_Candidate

Please review it and if you like it, we can add it to Mockups&Designs page. 

Please consider that there are a lot of views, and I didn't study all of them, we'll need to start discussing them too!

Hope you'll like them!

Best,
Onat

**Comment by ecada** [comment]
I liked your mockup designs a lot and I agree with nearly all of the pages but I believe a home page which shows the latest created living items or latest annotations would look better than a notifications page. By this way we encourage the user to annotate and discover existing  new living items . In addition to that I'm not that sure about showing annotations as pop-up views. A list of annotations might be better but we should discuss this topic at our upcoming meeting and elaborate after requirement elicitation phase.

**Comment by onatbas** [comment]
You might be right on showing the posts, but it might be a pain in the a** if we're trying to show annotations on slide view, there's going to be maths involved for calculating the positions etc, so it might just complicate things. But we can show items as theyre, without annotations whatsoever, that'd be cool. 

About the pop-up, i don't know about a list truly, we have to explicitly show from which target this annotation is being viewed. My proposition is, not a list of everything, but showing in left side panel(just like adding annotation) on click to yellow area. this will even simplify things! And we can list the annotations with same target there, as a list.  I'll create a mockup to show what i mean.

**Comment by onatbas** [comment]
Yes, I added the mockup showing a list-view of annotations on the same target. This looks nice, really.
I'll try to create an alternative on home page as well.

**Comment by onatbas** [comment]
I'm closing this as everyone seems ok with this. Candidate page has been moved to published page.
