### ISSUE TITLE
Deciding on mobile app framework

### ISSUE THREAD

**Issue by SelinGungor** [SWE574-Nerds/friendly-eureka#15]
Which mobile app framework should we use for developing mobile application?

I suggest to use https://ionicframework.com/. Ionic is an HTML5 mobile framework with focus on performance. It also does not require third-party JS library.

Ionic framework has very good documentation https://ionicframework.com/docs/, 
and rich IU components. https://ionicframework.com/docs/components/#overview

What are your thoughts on this?

**Comment by ecada** [comment]
Ionic is definitely a wonderful framework but I think we should stick to Android. Native Android mobile application would be a better option than a 3rd party framework.

**Comment by onatbas** [comment]
I'll definitely recommend Ionic. 

1. First, Ionic is VERY easy to use. You don't need to wire up some emulator etc.
2.  it's web-based, not everybody is used to mobile-native stack.
3. This might help us get some code reuse out of it, and everybody is familiar with web stack, familiarity is a good thing to have when we're developing.
4. Ionic applications are easy to demo. This is not technical at all, but we're doing product development and these things matter. We're going to show our progress in class etc. and being able to easily show it is a plus imho.

**Comment by umurtrky** [comment]
I have never used Ionic before. It looks quite nice. It is web based and this is the best thing about it for me. I am not familiar with mobile platforms so that makes it a good option. So I am okay with it. One of the aims of this project is to learn new things, right?

**Comment by ecada** [comment]
In out last meeting on September 3rd we finalized our discussion on this issue. Everyone agreed to use Android therefore I'm closing this topic.
