### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#16]
Now that we have an overall definition for the server-side, We can start studying the db schema. I'll create a draft and open it to discussion at decided.

**Comment by ecada** [comment]
I've started preparing a draft for ER-diagrams.

**Comment by ecada** [comment]
Below is my ER diagram of the project. I certainly think that it'll be updated in the future but it will form a basis. 
<img width="1232" alt="screen shot 2017-10-10 at 20 28 31" src="https://user-images.githubusercontent.com/18642218/31414890-cc845814-ae28-11e7-8137-a85f5279b2f1.png">
