### ISSUE TITLE
Create Use-case diagrams 

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#17]
First, we have to decide on the use-cases for back-end use-cases. 

Let's have a discussion on it and have a list of use-cases and divide it up among the team.

**Comment by muharremunver** [comment]
User: 
Register                Create & Edit & Delete history items
Login                    Create & Edit & Delete annotations
Edit profile            View history items' detail.
Search items

Admin: Create & Edit & Delete all objects in the system such as users, posts, parameters.

**Comment by SelinGungor** [comment]
Django supports very useful admin console, right? So, we don’t have to do too much work on that side I guess.

Should we create different use cases for mobile? We talked that user might not be able to create annotation using mobile, just adding notes or reminder for annotations.

**Comment by onatbas** [comment]
Yes, django admin console is pretty extensive. İ think we can tag the use cases as to which platform they apply to.
Possible example notation:
Use case one (mobile, web)

Best,
Onat
