### ISSUE TITLE
Use case diagram of Eureka - Living History Items

### ISSUE THREAD

**Issue by SelinGungor** [SWE574-Nerds/friendly-eureka#19]
Hi Team,

I've created a use case diagram to define the scope of our system.

![Use case diagram](https://github.com/SWE574-Nerds/friendly-eureka/blob/master/design/usecasediagrams/UseCaseDiagramEureka.png?raw=true)

Wiki link: https://github.com/SWE574-Nerds/friendly-eureka/wiki/Use-case-diagram-of-Eureka--living-history-items

Please review and let me know of your thoughts!

Cheers,
Selin

**Comment by onatbas** [comment]
Thank you, that looks really nice. However, I have some comments:

1. Just to clarify, this is around living history items, right? There's also the notification part of the algorithm that's just as big as that.
2. I don't think the initial plan is to upload sound/video. Our current plan is to just leverage exeternal resources, or did I get it wrong?

**Comment by onatbas** [comment]
Can you also give a link to this in the wiki, please? I'm very happy to accept this for the "official" documentation 🥇 and I'm sure the rest of the team also will be.

**Comment by SelinGungor** [comment]
Thanks for your comments Onat. I wanted to mention that user may supply audio, video or image  when user is creating a living history item. "Upload" keyword is just used for external urls. There is one more use-case balloon which indicates user can only upload form external url.

**Comment by SelinGungor** [comment]
Administrator as inheriting, or more precisely generalizing the User, we are declaring that the Administrator can do everything that the User can do.

Use case diagram is fixed, so I close this issue.
