### ISSUE TITLE
Name of our project/repository

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#2]
Hi!

As discussed in our meeting, let's discuss the name for our project, shall we (as this random name might not be a good fit :) )? Any suggestions?

**Comment by SelinGungor** [comment]
Calculators? :)

**Comment by onatbas** [comment]
:) Tbh, This current name has really been ok with me. So I'll recommend Eureka!

**Comment by onatbas** [comment]
This has been talked on another platform. The whole team agrees on Eureka.
