### ISSUE TITLE
Research The Web Annotation Data Model

### ISSUE THREAD

**Issue by muharremunver** [SWE574-Nerds/friendly-eureka#3]
Let's investigate The Web Annotation Data Model & Annotation tools and share our experience with others

**Comment by onatbas** [comment]
Hello, everyone!  I've created a wiki page to document WEB Annotation Model and relevant stuff to our situation. You may find it in our Wiki. 

https://github.com/SWE574-Nerds/friendly-eureka/wiki/Web-Annotation-Model

I'm marking this one as closed.
