### ISSUE TITLE
HAXM is only officially supported up until MacOS 10.12 (Sierra) 

### ISSUE THREAD

**Issue by ecada** [SWE574-Nerds/friendly-eureka#31]
I started developing the Android version on my brother's computer(MacOS 10.12 Sierra). When I transferred the package to my own computer (MacOS 10.13 High Sierra official release), I've encountered a vast problem. HAXM is not supported bu High Sierra Beta.

**Comment by ecada** [comment]
"Technically HAXM is only officially supported up until MacOS 10.12 (Sierra) . Since MacOS 10.13 is still in beta, there may be a bug or incompatible API. If the wizard does no work, please file a bug here for the Android Emulator dev team to investigate further:

https://forums.developer.apple.com/thread/79172
https://blog.celogeek.com/201708/672/android-studio-emulator-haxm-on-mac-os-high-serria-10-13/
"

I tried 2 methods for this problem but still the virtual simulator doesn't work. I will continue the development on my brother's computer.  

Conclusion: Don't update to High Sierra even if it's an official release.

**Comment by onatbas** [comment]
I'll make sure I don't update thanks. But a question, Is this going to affect our progress?

**Comment by ecada** [comment]
No, It won't I can run it on my brother's computer. Nothing will change at all.
