### ISSUE TITLE
Tag format should be supported for categories. 

### ISSUE THREAD

**Issue by ecada** [SWE574-Nerds/friendly-eureka#48]
User shall be able to create new tags and choose from the tags that were previously specified.

**Comment by onatbas** [comment]
Done. 
How it looks on creation
<img width="596" alt="screen shot 2017-11-30 at 21 15 09" src="https://user-images.githubusercontent.com/714795/33447272-d8f1ac7e-d613-11e7-8529-c478da0da6af.png">

How it looks on detail.
<img width="217" alt="screen shot 2017-11-30 at 21 16 23" src="https://user-images.githubusercontent.com/714795/33447273-d91cb2fc-d613-11e7-9e65-0e483efe725e.png">

API documentation is also updated.
