### ISSUE TITLE
Deciding on the project management methodology 

### ISSUE THREAD

**Issue by ecada** [SWE574-Nerds/friendly-eureka#6]
I believe Scrum methodology is best suited for this project what do you think?

**Comment by SelinGungor** [comment]
I think we should choose one of Agile Methodologies. We may use Scrum or Kanban, because both of them allow large tasks to be broke down.

**Comment by onatbas** [comment]
Let's do Scrum I say. Kanban is more of a maintainer type of process. We literally don't have anything to work with in these early processes. The need for deliverables in first few weeks is huge. Just my two cents but I say let's do Scrum.

**Comment by SelinGungor** [comment]
I agree with doing scrum. Probably, we will have one week iterations. We may adjust scrum events to our workflow and name it eurekascrum! :)

**Comment by onatbas** [comment]
I don't think the rest of the team will object to this, so I'm marking this complete. Let's open this up if other opinions arise.
