### ISSUE TITLE
Searching for time should take ranges into account.

### ISSUE THREAD

**Issue by onatbas** [SWE574-Nerds/friendly-eureka#64]
Given there's a listory with a timeInfo ranging between 2000 and 2010
When a user sends in a keyword such as 2005
Then the listory with a timeInfo ranging between 2000 and 2010 should also be found and returned.

Please see the comments on searching on issue #59 

Please revisit the algorithm such that if a listory has more than one timeInfo fields, it should check for this behaviour (see pseudo code):

```
if  timeInfo.valueCount > 1 and keyword.isdigit() and keyword bigger than value_1 && keyword smaller than value_2
        then SUCCESS
```

**Comment by ecada** [comment]
My last pull request offers a solution to this problem. I will really appreciate if you just take a quick look and offer your thoughts on it.

**Comment by onatbas** [comment]
There is no code to address this pushed to the repository.

I have reviewed the code, tested with it and gave you my feedback, but your response was to deny them and say "no it's not like that". I'll not pursue the merge on this branch furthermore as i see little opportunity there.

Onat Bas

**Comment by ecada** [comment]
Could you please elaborate on how this below is not a code that addresses this issue and where exactly you have offered your thoughts on this specific issue where I said "no it's not like that" in return?

+
 +    ) | Post.objects.filter(Q(word.isdigit())&Q(timeInfoGroup_timeInfo_value_count__gt = word)&Q(timeInfoGroup_timeValue1__lt=word)&Q(timeInfoGroup_timeValue2__gt=word) for word in keywords)
 +

**Comment by ecada** [comment]
I've created a new pull request that addresses the issue on a brand new branch and I've tested it on my localhost.

**Comment by ecada** [comment]
https://github.com/SWE574-Nerds/friendly-eureka/pull/79/commits/9c78abd688e64fe1c73db406d16e1a277c330b02

**Comment by ecada** [comment]
#78

**Comment by ecada** [comment]
I would really appreciate if you check #78  on this issue.
