### ISSUE TITLE
Deciding on Project Planning Tools 

### ISSUE THREAD

**Issue by ecada** [SWE574-Nerds/friendly-eureka#7]
The tool should include a Gantt chart so that we are able to see the dependencies between assigned project tasks. 

Which tools will you use for personal and team logs?

**Comment by SelinGungor** [comment]
we may use [projectlibre](http://www.projectlibre.com/) or [Orangescrum](https://www.orangescrum.org). Both of them supports Gantt chart feature.

**Comment by onatbas** [comment]
I'm ok with any tool, but craft.io imo is a great tool. It has all stuff for PM needs plus, it's free for single project. 

For issue tracking, let's stick with github issues/projects as discussed in the meeting.

<img width="1206" alt="screen shot 2017-09-24 at 13 31 45" src="https://user-images.githubusercontent.com/714795/30781710-c60fc382-a12c-11e7-8a61-f7d1d624fe35.png">

**Comment by onatbas** [comment]
I had a look. projectlibre and orangescrum are both paid tools with free-trials. craft.io is free. Is everyone ok with using that ?

**Comment by umurtrky** [comment]
Firstly, I am okay with craft.io. But still I would like to mention that I used [GanttPRO](https://ganttpro.com/) and I like it. It is online and if they did not change their style, it is free for a single project. If you want to see an example you can see the project plan that I created from [here](https://app.ganttpro.com/shared/token/d768bb465b085b40e3db499c765bce9f44e582b11b93a3d86eacf96f69f9a967#!/app/home).

**Comment by onatbas** [comment]
That looks promising, indeed. I'm OK with, both. I'll ask the team to jump in and decide, please. 

https://app.craft.io/share/05ADC1192305843009761318613

<img width="200" alt="screen shot 2017-09-25 at 12 49 38" src="https://user-images.githubusercontent.com/714795/30802877-812695c4-a1f0-11e7-89a0-db9e3047c390.png">
<img width="200" alt="screen shot 2017-09-25 at 12 49 40" src="https://user-images.githubusercontent.com/714795/30802879-83c299cc-a1f0-11e7-94be-6c3abccd375a.png">

**Comment by muharremunver** [comment]
As far as I used, GanttPro is useful tool to create project plan. On the other hand, carft.io looks better for other PM works. We can use the best functions of both two tools.  But, If we use just one tool for whole project, I prefer craft.io

**Comment by ecada** [comment]
Onat showed us Craft.io in our last meeting this week. I also agree that it is suited and sufficient for our needs. GantPRO definitely looks promising but I will go with craft.io on this one too. I guess our decision is finalized thus I'm closing this issue.
