### ISSUE TITLE
Selecting an item from search shows incorrect body of Listory

### ISSUE THREAD

**Issue by uskudarli** [SWE574-Nerds/friendly-eureka#80]
I made a few searches, and see that the body shown after I select a results is incorrect.

For example, I search for "sahlep", the list of item looks fine, but when selected you can see the image is correct but the body text is not. The text it shows (incorrect text) is:

_

> kadikoy'den kalkip besiktas'a giden vapur. ilk vapur seferi sabah 6:45**'tedir. bu saatten itibaren yarim saat arayla her saati 15 ve 45 gece kalkar bu vapur. sonuncu sefer ise yazin 20:45'te, kisin 20:15'tedir.ögrenci ve çalisan yogun seferleri 07:45 ve 08:15 olan vapur. geç kalanlar 08:45, geç kalmak umrunda olmayan tembel tenekeler de 09:15'i tercih eder..\nsabah uykusu için ideal mekanlardandır..

instead of:

> Tamam tamam, tek adres degil, ama saglam adres. Haci Muhiddin, Kadikoy. Hem ortam sahane, hem sahlep gibi sahlep. Eski usul. Son zamanlarda yerlesmis sahlep bozuntusu tozlarda degil asla. I tried to mark it on the map, but I think I failed :(

_

![image](https://user-images.githubusercontent.com/1347035/34727266-778c57ea-f567-11e7-94cd-b4483ce1116e.png)

**Comment by uskudarli** [comment]
sorry about the overblown image width and size

**Comment by onatbas** [comment]
@uskudarli Thank you for addressing this and documenting clearly. 

I was able to reproduce this issue, and have provided a fix for it in commit 84d937e. As a hotfix, the change is applied and deployed. You may test it in the live environment.
