### ISSUE TITLE
Review Requirements

### ISSUE THREAD

**Issue by muharremunver** [SWE574-Nerds/friendly-eureka#9]
Analyze the requirements and do not hesitate to modify them.

**Comment by onatbas** [comment]
Hello, everybody! I've created some requirements on the page. Please review and comment on them if you don't like'em. I appreciate it! Don't hesitate to delete if we don't like it, I'm ok with it :)

Thanks.

**Comment by muharremunver** [comment]
1. Shall we add a requirement like below?
"Users can enable the annotations they want to see and can disable the rest."              

2. Can users share an item whose content is completely text a.

**Comment by onatbas** [comment]
Hi. I think I agree with the first one, maybe a simple toggle to turn highlights on & off might be useful, to simply view the history item. I'm not sure about turning on&off based on type though. Might be too tricky for users to use.

**Comment by ecada** [comment]
Hello, 
I added requirements in the Annotations Section and created a Searching section and added a requirement in that field. 
@muharremunver I think we should add that requirement after the Requirement Elicitation phase. Some parts need to be clarified  before specifying the constraints. 
I'm not so sure about the pop-up view when displaying the annotations.Maybe a list of annotations in a section next to the living history item might be better suited. I definitely agree with all the other requirements and thanks for all the effort you've put into it.
